on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/hello-world-docker-action@v1
        with:
          greet: 'Alok'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Get the output one more time
        run: echo "The time was ${{ steps.hello.outputs.time }}"     
  bye_job:
    if: ${{ github.ref == 'refs/heads/main' }} # only deploy from 'main'
    runs-on: ubuntu-latest
    name: a_job_to_say_bye
    needs: [hello_world_job]
    steps:
      - name: Get the output one more time coming from second job
        run: echo "The time was ${{ steps.hello.outputs.time }}"
   
